apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: CBCI_Demo
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: CBCI
        kind: build
        with:
          url: https://core.cloudbees.guru/shared-demos/
          username: admin
          token: ${{secrets.CBCI_Guru_Token}}
          job-name: new_functionality_demo/job/workspace-cache/job/cache-off
