apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My First Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world 1234!"
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://golang:1.20.3-alpine3.17
        name: Compute version
        id: compute-version
        shell: sh
        run: |
          cat version > $CLOUDBEES_OUTPUTS/version
      - uses: my-gha-run
        name: GHA-Run
        with:
          repo-name: platfrom_learning
          branch-name: main
          workflow-name: CI
    outputs:
      version: ${{ steps.compute-version.outputs.version }}
  deploy:
    environment: dev
    steps:
      - uses: docker://golang:1.20
        name: Pretend to deploy
        run: echo "Pretending to deploy version ${{needs.build.outputs.version}} to
          namespace ${{vars.DEPLOY_NAMESPACE}} using token
          ${{secrets.DEPLOY_TOKEN}}"
    needs:
      - build
